VB-master/VB-master/Controllers/FourController.cs
using Microsoft.AspNetCore.Mvc;

namespace VB.Controllers
{
    public class FourController : Controller
    {
        public IActionResult FourthView()
        {
            return View();
            
        }
    }
}

VB-master/VB-master/Views/Four/FourthView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewData["Title"] = "FourthView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@* <h1>Employee Apreciation</h1> *@
<div class="bg-1">
    <div class="container text-center">
        @* <h3>Doctor of the month</h3> *@
        <br />
        <img src="~/css/Nandi.jpg" alt="Nandi" width="350" height="350">
        <br />
        <div>
            <h3>Congadulation to:</h3>
            <h3> Doctor Magudumane</h3>
            <h3>She is Doctor of the month</h3>
            <h3>We appreciate your services</h3>
        </div>
        
    </div>
</div>
<div class="container">
    <section class="main">
        <div class="main-top">
           @*  <h1>Hello Mommy </h1> *@
            <i class="fas fa-user-cog"></i>
        </div>
        <div class="main-skills">
            <div class="card">
                <h3>Counseling</h3>
                <p>Doctors need help too.</p><br />
                <br/>
                <br />
                <button>Book</button>
            </div>
            <div class="card">
                <h3>Team Building</h3>
                <p>1 September 2024 <br /> 120/80</p>
                <br />
                <br />
                <br />
                <button>RSVP</button>
            </div>
            <div class="card">

                <h3>Sugestions</h3>
                <p>We value your opinion<br />66 CM</p>
                <br />
                <br /><button>Write a sugestion</button>
            </div>

            @* <div class="card">
                <h3>Pregnancy Term </h3>
                <p>10 weeks</p><br />
                <button>View</button>
            </div> *@
        </div>
    </section>
</div>

@* the calender
 *@
<br />
@* <br />
<br />
<br /> *@

<h1>Daily schedule</h1>

<div class="month">
    <ul>
        <li class="prev">&#10094;</li>
        <li class="next">&#10095;</li>
        <li>
            August<br>
            <span style="font-size:18px">2023</span>
        </li>
    </ul>
</div>

<ul class="weekdays">
    <li>Mo</li>
    <li>Tu</li>
    <li>We</li>
    <li>Th</li>
    <li>Fr</li>
    <li>Sa</li>
    <li>Su</li>
</ul>

<ul class="days">
    <li>1</li>
    <li>2</li>
    <li>3</li>
    <li>4</li>
    <li>5</li>
    <li>6</li>
    <li>7</li>
    <li>8</li>
    <li>9</li>
    <li><>10</li>
    <li>11</li>
    <li>12</li>
    <li>13</li>
    <li>14</li>
    <li>15</li>
    <li>16</li>
    <li>17</li>
    <li>18</li>
    <li>19</li>
    <li>20</li>
    <li><span class="active" asp-controller="Four" asp-action="FourthView">21</span></li>
    <li><span class="active" asp-controller="Four" asp-action="FourthView">22</span></li>
    <li><span class="active" asp-controller="Four" asp-action="FourthView">23</span></li>
    <li><span class="active" asp-controller="Four" asp-action="FourthView">24</span></li>
    <li><span class="active" asp-controller="Four" asp-action="FourthView">24</span></li>
    <li>26</li>
    <li>27</li>
    <li>28</li>
    <li>29</li>
    <li>30</li>
    <li>31</li>
</ul>